services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: qtrixnet/backend-docker-and-compose-v9
    ports:
      - '4000:3000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - internal

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: qtrixnet/frontend-docker-and-compose-v9
    ports:
      - '8081:80'
    restart: always
    networks:
      - external

  db:
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - ./pg-data:/var/lib/postgresql/data/pgdata
    networks:
      - internal
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
  external: